# Generated by Django 5.1.1 on 2024-09-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ecommerce', '0005_clothes_size_shoes_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
