# Generated by Django 5.1.1 on 2024-09-05 09:38

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from ecommerce.models import Clothes, Shoes

def populate_polymorphic_ctype(apps, schema_editor):
    Product = apps.get_model('ecommerce', 'Product')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType IDs for each model
    product_ct = ContentType.objects.get_for_model(Product)
    clothes_ct = ContentType.objects.get_for_model(Clothes)
    shoes_ct = ContentType.objects.get_for_model(Shoes)

    for product in Product.objects.all():
        if isinstance(product, Clothes):
            product.polymorphic_ctype = clothes_ct
        elif isinstance(product, Shoes):
            product.polymorphic_ctype = shoes_ct
        else:
            product.polymorphic_ctype = product_ct
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_clothes_options_alter_shoes_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_polymorphic_ctype),
    ]
