# Generated by Django 5.1.1 on 2024-09-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_name_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
