# Generated by Django 5.1.1 on 2024-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_orderproduct_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=70),
        ),
    ]
